version: '2.4'
services:

  nodejs:
    env_file:
    - .env
    build:
      context: ./
    command: npm run start.dev
    volumes:
      - ./:/usr/src/app
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_PARAMS: ${MONGO_PARAMS}
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 27017:27017