version: '2.4'
services:

  nodejs:
    env_file:
    - .env
    build:
      context: ./src/
    command: npm run start.dev
    ports:
      - 9229:9229
    volumes:
      - ./src/:/usr/src/app
    depends_on:
      mongo:
        condition: service_healthy
      postgres:
        condition: service_started

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 27017:27017

  postgres:
    env_file:
    - .env
    image: postgres:11.2-alpine
    ports:
    - 5432:5432